name: Build Project with Gradle

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
  pull_request:

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
  build:
    needs:
      - validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: gradle/gradle-build-action@v2.4.2
        name: Check with ktlint
        with:
          arguments: ktlintCheck
      - uses: gradle/gradle-build-action@v2.4.2
        name: Build with Gradle
        with:
          arguments: classes
